#!/bin/csh -f


rm -rf ./live.txt

wget https://raw.githubusercontent.com/wolfcode9/OpenChannel/main/live.txt
          
grep -i "ubvip1688" ./live.txt > ./Source/ubvip1688



#set lineEndNum = `wc -l ./live.txt`
#echo $lineEndNum


set keyLineNum = `grep -n "台灣頻道" ./live.txt`
echo $keyLineNum

#set lineLength = `echo "($lineEndNum - $keyLineNum)"`

#tail -n $keyLineNum ./live.txt > UBSP


#sed -n '$keyLineNum, $linEndNum.p' ./live.txt

sed -n '/安博台灣/,//p' ./live.txt > UBSP

sed -i '/探索科學/d' ./UBSP
sed -i '/探索頻道/d' ./UBSP
sed -i '/CBN歡笑劇場/d' ./UBSP
sed -i '/天映經典/d' ./UBSP
sed -i '/靖天映畫/d' ./UBSP
sed -i '/Z頻道/d' ./UBSP


file -i UBSP

cat ./UBSP | grep -v "#genre" | grep -v "header" | cut -d "," -f 1 > a
cat ./UBSP | grep -v "#genre" | grep -v "header" | cut -d "," -f 1 | cut -d " " -f 1 > b
foreach chk ("`cat ./a`")
  echo $chk
  set c = `echo $chk | cut -d " " -f 1` 
  echo $c
  sed -i 's/'"$chk"'/'"$c"'/' ./live.txt
end

sed -n '/安博台灣/,//p' ./live.txt > UBSP


set FP = "./UBSP"

foreach file (./UBSP ./Source/ubvip1688)

sed -i '/#genre#/d' $FP
sed -i 's/台,/,/' $FP
sed -i 's/TVN台灣版/tvN/' $FP
sed -i 's/ELTA/愛爾達/' $FP
sed -i 's/壹新聞/壹電視新聞/' $FP
sed -i 's/一,/,/' $FP
sed -i 's/二,/,/' $FP


end

