#!/bin/csh -f
  
rm -rf output

  
touch output

#echo `cat ./0_TW | sed '/台灣,#genre#/d'

cat 0_TW | grep -v genre | cut -d "," -f 1 > list

foreach chk ("`cat list`")
 #echo $chk > chk

 grep -i $chk ./TW > parsing_TW                                                                                                                                                          
#end
  
  
#cat ./report_from_primetime | head -n 5
